version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8091:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - network

  selenoid:
    image: "aerokube/selenoid:latest-release"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - selenoid-video:/opt/selenoid/video
      - ./config:/etc/selenoid/
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/videos/
    command: ["-limit", "1", "-session-attempt-timeout", "120s"]
    ports:
      - "4444:4444"
    networks:
      - network

  selenoid-ui:
    image: aerokube/selenoid-ui
    ports:
      - "8082:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - network

  firefox:
    image: "selenoid/firefox:latest"
    environment:
      - "ENABLE_VNC=true"
      - "SCREEN_RESOLUTION=1920x1080x24"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - network

  opera:
    image: "selenoid/opera:latest"
    environment:
      - "ENABLE_VNC=true"
      - "SCREEN_RESOLUTION=1920x1080x24"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - network

volumes:
  jenkins-data:
  selenoid-video:

networks:
  network: