version: "3.9"
services:
  myjenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8090:8080"
    networks:
      - network
    container_name: jenkins

  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/da/IdeaProjects/PracticalTask/config:/etc/selenoid/
    command: ["-conf", "/etc/selenoid/browsers.json"]
    ports:
      - "4444:4444"
    networks:
      - network
    container_name: selenoid

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.9
    ports:
      - "8082:8080"
    environment:
      - "SELENOID_URI=http://selenoid:4444"
    networks:
      - network
    container_name: selenoid-ui

  selenoid-opera:
    image: selenoid/opera:latest
    networks:
      - network
    container_name: selenoid-opera

  selenoid-chrome:
    image: selenoid/chrome:latest
    networks:
      - network
    container_name: selenoid-chrome
    volumes:
      - "/tmp/video:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video"
      - "ENABLE_VIDEO=true"
      - "VIDEO_NAME=${BROWSER}_${TEST_NAME}_${BUILD_NAME}.mp4"

  selenoid-firefox:
    image: selenoid/firefox:latest
    networks:
      - network
    container_name: selenoid-firefox
    volumes:
      - "/tmp/video:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video"
      - "ENABLE_VIDEO=true"

  selenoid-video-recorder:
    image: selenoid/video-recorder:latest-release
    networks:
      - network
    container_name: selenoid-video-recorder
    volumes:
      - "/tmp/video:/opt/selenoid/video"
    environment:
      - "S3_ENABLED=false"
      - "OUTPUT_DIR=/opt/selenoid/video"
      - "CLEANUP_SECS=3600"
      - "FRAME_SIZE=1280x720"
      - "FRAME_RATE=25"
      - "VIDEO_CODEC=libx264"

networks:
  network:
