version: "3.9"

services:
  myjenkins:
    image: myjenkins-blueocean:2.375.3-1
    ports:
      - "8090:8080"
    networks:
      - selenoid
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_CERTDIR=""
    depends_on:
      - docker
    restart: always

  docker:
    image: docker:dind
    privileged: true
    networks:
      - selenoid
    container_name: docker
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - "./config:/etc/selenoid"
      - "./target:/output"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid" ]

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.9
    ports:
      - "8082:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - selenoid
    container_name: selenoid-ui

  selenoid-chrome:
    image: selenoid/chrome:latest
    networks:
      - selenoid
    container_name: selenoid-chrome
    volumes:
      - "/tmp/video:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video"
      - "ENABLE_VIDEO=true"
      - "VIDEO_NAME=${BROWSER}_${TEST_NAME}_${BUILD_NAME}.mp4"
    depends_on:
      - selenoid
      - selenoid-ui

  selenoid-firefox:
    image: selenoid/firefox:110.0
    networks:
      - selenoid
    container_name: selenoid-firefox
    volumes:
      - "/tmp/video:/opt/selenoid/video"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video"
      - "ENABLE_VIDEO=true"
      - "VIDEO_NAME=${BROWSER}_${TEST_NAME}_${BUILD_NAME}.mp4"
    depends_on:
      - selenoid
      - selenoid-ui
networks:
  selenoid:
    external:
      name: selenoid

volumes:
  jenkins_home:
